import os
import django
from django.db import connection

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'A_Helping_Hand.settings')
django.setup()

# ****COMMENTED OUT BECAUSE CUSTOMER TABLE IS ALREADY CREATED****
# connection.cursor().execute("CREATE TABLE Customer(customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY," +
#          "first_name VARCHAR2(50) NOT NULL," +
#          "last_name VARCHAR2(50) NOT NULL," +
#  		"password  VARCHAR2(40)  NOT NULL," +
#  		"phone_number VARCHAR2(11)," +
#  		"thana_name VARCHAR2(30) NOT NULL," +
#  		"address VARCHAR2(70)," +
#  		"date_of_birth DATE NOT NULL," +
#  		"rating NUMBER(2,1) CHECK (rating BETWEEN 0.0 AND 5.0)," +
#          "PRIMARY KEY(customer_id));")

# TODO FARDIN 1 : CREATE ALL TABLES FOLLOWING OUR SCHEMA

# TODO FARDIN 0 : REMEMBER TO PULL FROM GITKRAKEN